//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public System.DateTime AssetBoughtDate { get; set; }
        public Nullable<decimal> AssetPrice { get; set; }
        public string AssetStatus { get; set; }
        public string AssetLocation { get; set; }
    }
}
