//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workflow()
        {
            this.WorkflowStatus = new HashSet<WorkflowStatu>();
        }
    
        public int WorkflowID { get; set; }
        public string WorkflowName { get; set; }
        public string Description { get; set; }
        public string RelatedDepartment { get; set; }
        public string Steps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStatu> WorkflowStatus { get; set; }
    }
}
